export default {
    REMOVE_CART: "REMOVE_CART",
    ADD_CART: "ADD_CART",
    UP_VOTE: "UP_VOTE",
    DOWN_VOTE: "DOWN_VOTE",
    ORDER_BY_ASC: "ORDER_BY_ASC",
    ORDER_BY_DESC: "ORDER_BY_DESC",
    ORDER_BY_DEFAULT: "ORDER_BY_DEFAULT"
};